### PR TITLE
feat(about): Provide build info

### PR DESCRIPTION
**Pull request by lordrip**
`VSCode` implementation of https://github.com/KaotoIO/kaoto-ui/pull/2228

#### Before
Screenshot from 2023-08-04 11-32-38

#### After
Screenshot from 2023-08-04 11-32-00

### CODE REVIEW

**Comment by djelinek** [comment]
HI @lordrip , may I ask how I can test locally? because I was trying to build your branch with stable and also main branch of kaoto-ui and I can't still see more build info inside About dialog
image

**Comment by djelinek** [comment]
ok, I see the PR-2228 is not merged yet.. sorry I missed that

**Comment by djelinek** [comment]
+1 when kaoto-ui will be ready, I like this kind of more information inside About page 🙂

**Comment by lordrip** [comment]
I'm closing this pull request until we figure it out on the kaoto side :)

**Pull request closed without merging**
